# Provisioned Perses resources: the default Prometheus datasource.
apiVersion: v1
kind: ConfigMap
metadata:
  name: perses-provisioning
data:
  datasource.json: |
    {
      "kind": "GlobalDatasource",
      "metadata": {"name": "prometheus"},
      "spec": {
        "default": true,
        "plugin": {
          "kind": "PrometheusDatasource",
          "spec": {"directUrl": "http://kps-prometheus.k8ost-monitoring.svc:9090"}
        }
      }
    }
