apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: ${name}
spec:
  instances: ${instances}
  imageName: ${image}
  storage:
    size: ${storage}
${resources}${extra}  probes:
    readiness: {periodSeconds: 3, failureThreshold: 2}
    liveness: {periodSeconds: 3, timeoutSeconds: 3, failureThreshold: 2}
