        - alert: ${alert}
          expr: '${expr}'
          for: 2m
          labels: {severity: warning, cluster: ${name}}
          annotations: {summary: "${summary}", runbook_url: "${runbook}"}
